Ecommerce\BKBundle\Entity\City:
  type: entity
  table: city
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    active:
      type: boolean
      nullable: true
    municipalityCode:
      type: integer
      unsigned: false
      nullable: true
      column: municipality_code
    lat:
      type: decimal
      nullable: true
    lng:
      type: decimal
      nullable: true
    areacode:
      type: string
      length: 10
      fixed: false
      nullable: true
  oneToOne:
    municipality:
      targetEntity: City
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        municipality_id:
          referencedColumnName: id
      orphanRemoval: false
    province:
      targetEntity: Province
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        province_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
