Ecommerce\BKBundle\Entity\ProductCategory:
  type: entity
  table: product_category
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    subcategory:
      targetEntity: Subcategory
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        subcategory_id:
          referencedColumnName: id
      orphanRemoval: false
    product:
      targetEntity: Product
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        product_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
