Ecommerce\BiologischekaasBundle\Entity\Attribute:
  type: entity
  table: attribute
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    isFilterable:
      type: integer
      length: 2
      fixed: false
      nullable: false
      column: is_filterable
  lifecycleCallbacks: {  }
