Ecommerce\BiologischekaasBundle\Entity\Product:
  type: entity
  table: product
  repositoryClass: Ecommerce\BiologischekaasBundle\Repository\ProductRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    description:
      type: text
      nullable: false
    sku:
      type: string
      length: 50
      fixed: false
      nullable: false
    keywords:
      type: string
      length: 255
      fixed: false
      nullable: true
    salePrice:
      type: decimal
      nullable: true
      column: sale_price
    price:
      type: decimal
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at
    soldAt:
      type: datetime
      nullable: true
      column: sold_at
    permalink:
      type: string
      length: 255
      fixed: false
      nullable: false
    stock:
      type: integer
      unsigned: false
      nullable: false
    views:
      type: integer
      unsigned: false
      nullable: false
    isNew:
      type: boolean
      unsigned: false
      nullable: false
      column: is_new
    active:
      type: integer
      unsigned: false
      nullable: false
    isSale:
      type: boolean
      unsigned: false
      nullable: false
      column: is_sale
    weight:
      type: integer
      unsigned: false
      nullable: true
    firstImage:
      type: integer
      column: first_image
      nullable: true
  oneToOne:
    shippingType:
      targetEntity: ShippingTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipping_type_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToMany:
   attributes:
      targetEntity: ProductAttributes
      cascade: [ "persist", "remove" ]
      mappedBy: product
      orphanRemoval: false
  manyToMany:
    images:
      targetEntity: ProductImages
      cascade: {  }
      mappedBy: null
      inversedBy: product
      joinTable:
        name: product_images
        joinColumns:
          -
            name: product_id
            referencedColumnName: id
        inverseJoinColumns:
          -
            name: id
            referencedColumnName: id
      orderBy: null
    subcategories:
      targetEntity: Subcategory
      cascade: {  }
      mappedBy: null
      inversedBy: product
      joinTable:
        name: product_category
        joinColumns:
          -
            name: product_id
            referencedColumnName: id
        inverseJoinColumns:
          -
            name: subcategory_id
            referencedColumnName: id
      orderBy: null
  lifecycleCallbacks: {  }
