Page:
  type: entity
  table: page
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    content:
      type: text
      nullable: false
    image:
      type: string
      length: 255
      fixed: false
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    parent:
      type: integer
      unsigned: false
      nullable: false
    permalink:
      type: string
      length: 255
      fixed: false
      nullable: false
    status:
      type: integer
      unsigned: false
      nullable: false
    description:
      type: string
      length: 255
      fixed: false
      nullable: false
    keywords:
      type: string
      length: 255
      fixed: false
      nullable: false
    landingpage:
      type: integer
      unsigned: false
      nullable: false
    landingpageKeyword:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: landingpage_keyword
  lifecycleCallbacks: {  }
