Ecommerce\AVBundle\Entity\Newsletter:
  type: entity
  table: newsletter
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    content:
      type: text
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    sendAt:
      type: datetime
      nullable: false
      column: send_at
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    campainName:
      type: string
      length: 255
      fixed: false
      column: campain_name
      nullable: false
  ManyToMany:
    clients:
      targetEntity: Client
      mappedBy: null
      joinTable:
        name: newsletter_clients
        joinColumns:
          client_id:
            referencedColumnName: id
        inverseJoinColumns:
          newsletter_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }
