Ecommerce\AVBundle\Entity\OrdersComment:
  type: entity
  table: orders_comment
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    content:
      type: text
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
  oneToOne:
    order:
      targetEntity: Orders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        order_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
