parameters:
    database_driver:   pdo_mysql
    database_host:     addictedtovintage.nl
    database_port:     ~
    database_name:     addictedtovintage_nl
    database_user:     p3881
    database_password: blENblk2012

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    default_image:      /images/default.jpg
    sale_discount:      20
