jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Ecommerce\BiologischekaasBundle\Entity\Client:
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        clients:
            entity: { class: Ecommerce\BiologischekaasBundle\Entity\Client, property: email }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        client_login:
            provider: clients
            pattern:   ^/
            anonymous: ~
            form_login:
                default_target_path: /
                check_path: /login_check
                login_path: /login
            remember_me:
                key: %secret%
                lifetime: 15768000
                path: /
                domain: ~
            logout:
                path:   /logout
                target: /

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
