Shipping:
  type: entity
  table: shipping
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    costs:
      type: float
      nullable: false
    description:
      type: string
      length: 255
      fixed: false
      nullable: false
    active:
      type: boolean
      nullable: false
    isChecked:
      type: integer
      unsigned: false
      nullable: false
      column: is_checked
  lifecycleCallbacks: {  }
