SubcategoryCategory:
  type: entity
  table: subcategory_category
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
  oneToOne:
    subcategory:
      targetEntity: Subcategory
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        subcategory_id:
          referencedColumnName: id
      orphanRemoval: false
    category:
      targetEntity: Category
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
