Product:
  type: entity
  table: product
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    description:
      type: text
      nullable: false
    sku:
      type: string
      length: 50
      fixed: false
      nullable: false
    keywords:
      type: string
      length: 255
      fixed: false
      nullable: false
    salePrice:
      type: float
      nullable: false
      column: sale_price
    price:
      type: float
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    deletedAt:
      type: datetime
      nullable: false
      column: deleted_at
    soldAt:
      type: datetime
      nullable: false
      column: sold_at
    permalink:
      type: string
      length: 255
      fixed: false
      nullable: false
    stock:
      type: integer
      unsigned: false
      nullable: false
    views:
      type: integer
      unsigned: false
      nullable: false
    isNew:
      type: integer
      unsigned: false
      nullable: false
      column: is_new
    active:
      type: integer
      unsigned: false
      nullable: false
    isSale:
      type: integer
      unsigned: false
      nullable: false
      column: is_sale
    weight:
      type: integer
      unsigned: false
      nullable: true
  lifecycleCallbacks: {  }
