Ecommerce\BiologischekaasBundle\Entity\Province:
  type: entity
  table: province
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    active:
      type: boolean
      nullable: true
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
    lat:
      type: decimal
      nullable: true
    lng:
      type: decimal
      nullable: true
  oneToOne:
    country:
      targetEntity: Country
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        country_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
