Ecommerce\BiologischekaasBundle\Entity\Shipping:
  type: entity
  table: shipping
  repositoryClass: Ecommerce\BiologischekaasBundle\Repository\ShippingRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    costs:
      type: float
      nullable: false
    description:
      type: string
      length: 255
      fixed: false
      nullable: false
    active:
      type: boolean
      nullable: false
    isChecked:
      type: integer
      unsigned: false
      nullable: false
      column: is_checked
    country:
      type: string
      length: 2
      fixed: false
      nullable: false      
  oneToOne:
    shippingType:
      targetEntity: ShippingTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipping_type:
          referencedColumnName: id
      orphanRemoval: false      
  lifecycleCallbacks: {  }
