parameters:
#    ecommerce.example.class: AddictedToVintage\EcommerceBundle\Example

services:
    PageManager:
        class:     AddictedToVintage\EcommerceBundle\PageManager\PageManager
        calls:
            - [setContainer, ["@service_container"]]
    ShopManager:
        class:     AddictedToVintage\EcommerceBundle\ShopManager\ShopManager
        calls:
            - [setContainer, ["@service_container"]]
            - [initialize, []]
    ProductFilter:
        class:     AddictedToVintage\EcommerceBundle\ProductFilter\ProductFilter
        calls:
            - [setContainer, ["@service_container"]]
            - [initialize, []]
    adtv.twig.extension:
        class: AddictedToVintage\EcommerceBundle\Twig\Extension\FirstImageTwigExtension
        tags:
            - { name: twig.extension }            
            
    adtv.twig.extension2:
        class: AddictedToVintage\EcommerceBundle\Twig\Extension\PaginateTwigExtension
        tags:
            - { name: twig.extension }            
            
    adtv.twig.extension3:
        class: AddictedToVintage\EcommerceBundle\Twig\Extension\DayConvertTwigExtension
        tags:
            - { name: twig.extension }            
            
#    ecommerce.example:
#        class: %ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
