CartProducts:
  type: entity
  table: cart_products
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    amount:
      type: integer
      unsigned: false
      nullable: false
    price:
      type: float
      nullable: false
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
    createdAt:
      type: datetime
      nullable: false
      column: created_at
  oneToOne:
    product:
      targetEntity: Product
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        product_id:
          referencedColumnName: id
      orphanRemoval: false
    cart:
      targetEntity: Cart
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        cart_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
