AddictedToVintage\EcommerceBundle\Entity\Orders:
  type: entity
  table: orders
  repositoryClass: AddictedToVintage\EcommerceBundle\Repository\OrdersRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    ordernr:
      type: string
      length: 255
      fixed: false
      nullable: false
    status:
      type: string
      length: 50
      fixed: false
      nullable: false
    shippingCode:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: shipping_code
    shippingDate:
      type: datetime
      nullable: true
      column: shipping_date
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    payed:
      type: integer
      unsigned: false
      nullable: false
    total:
      type: float
      nullable: false
  oneToOne:
    paymethod:
      targetEntity: Paymethod
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        paymethod_id:
          referencedColumnName: id
      orphanRemoval: false
    coupon:
      targetEntity: Coupon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        coupon_id:
          referencedColumnName: id
      orphanRemoval: false
    client:
      targetEntity: Client
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        client_id:
          referencedColumnName: id
      orphanRemoval: false
    shipping:
      targetEntity: Shipping
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipping_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToMany:
    products:
      targetEntity: OrdersProduct
      cascade: [ "persist", "remove" ]
      mappedBy: order
      orphanRemoval: false
  lifecycleCallbacks: {  }
