AddictedToVintage\EcommerceBundle\Entity\Section:
  type: entity
  table: section
  repositoryClass: AddictedToVintage\EcommerceBundle\Repository\SectionRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    permalink:
      type: string
      length: 255
      fixed: false
      nullable: false
  manyToMany:
    categories:
      targetEntity: Category
      mappedBy: null
      joinTable:
        name: section_category
        joinColumns:
          section_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
 
  lifecycleCallbacks: {  }
