Ecommerce\AddictedtovintageBundle\Entity\Banner:
  type: entity
  table: banner
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    content:
      type: text
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
  lifecycleCallbacks: {  }
