Ecommerce\AddictedtovintageBundle\Entity\Paymethod:
  type: entity
  table: paymethod
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    isActive:
      type: integer
      unsigned: false
      nullable: true
      column: is_active
    isForeign:
      type: integer
      unsigned: false
      nullable: false
      column: is_foreign
    code:
      type: string
      length: 100
      fixed: false
      nullable: false
    description:
      type: string
      length: 255
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
