BiologischeKaas\EcommerceBundle\Entity\Invoice:
  type: entity
  table: invoice
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    totalPrice:
      type: float
      nullable: false
      column: total_price
    tax:
      type: float
      nullable: false
    payed:
      type: integer
      unsigned: false
      nullable: false
  oneToOne:
    client:
      targetEntity: Client
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        client_id:
          referencedColumnName: id
      orphanRemoval: false
    order:
      targetEntity: Orders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        order_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
