BiologischeKaas\EcommerceBundle\Entity\Subcategory:
  type: entity
  table: subcategory
  repositoryClass: BiologischeKaas\EcommerceBundle\Repository\SubcategoryRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    description:
      type: text
      nullable: false
    keywords:
      type: string
      length: 255
      fixed: false
      nullable: false
    image:
      type: string
      length: 255
      fixed: false
      nullable: true
    permalink:
      type: string
      length: 255
      fixed: false
      nullable: false
    active:
      type: integer
      unsigned: false
      nullable: false
  manyToMany:
    products:
      targetEntity: Product
      mappedBy: null
      joinTable:
        name: product_category
        joinColumns:
          subcategory_id:
            referencedColumnName: id
        inverseJoinColumns:
          product_id:
            referencedColumnName: id
    categories:
      targetEntity: Category
      mappedBy: null
      joinTable:
        name: subcategory_category
        joinColumns:
          subcategory_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
    
  lifecycleCallbacks: {  }
