Ecommerce\EcommerceBundle\Entity\Postcode:
  type: entity
  table: postcode
  repositoryClass: Ecommerce\EcommerceBundle\Repository\PostcodeRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    active:
      type: boolean
      nullable: true
    fourpp:
      type: integer
      unsigned: false
      nullable: true
    lat:
      type: decimal
      nullable: true
    lng:
      type: decimal
      nullable: true
  oneToOne:
    city:
      targetEntity: City
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        city_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
